using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace EndpointHelpers;

[Generator]
public sealed class LinkGeneratorGenerator : ControllerGeneratorBase
{
    protected override string GenerateAttributeName => "GenerateLinkGeneratorAttribute";
    protected override string IgnoreAttributeName => "LinkGeneratorIgnoreAttribute";
    protected override string OutputFileName => "LinkGeneratorExtensions.g.cs";

    protected override string BuildSource(
        IReadOnlyList<ControllerModel> selectedControllers,
        bool hasJetbrainsAnnotations = false)
    {
        var nonAreaControllers = selectedControllers
            .Where(static controller => string.IsNullOrWhiteSpace(controller.AreaName))
            .OrderBy(static controller => controller.MetadataName, StringComparer.Ordinal)
            .ToArray();

        var areaGroups = selectedControllers
            .Where(static controller => !string.IsNullOrWhiteSpace(controller.AreaName))
            .GroupBy(static controller => controller.AreaName!, StringComparer.Ordinal)
            .OrderBy(static group => group.Key, StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EndpointHelpersNamespace};");
        sb.AppendLine();

        foreach (var controller in selectedControllers)
        {
            var controllerName = controller.Name.Replace("Controller", string.Empty);
            var helperClassName = $"{controller.Name}LinkGenerator";

            sb.AppendLine($"public sealed class {helperClassName}(LinkGenerator linkGenerator)");
            sb.AppendLine("{");

            foreach (var method in controller.Methods)
            {
                var actionMethodName = $"Get{method.Name}Path";
                var parameters = string.Join(
                    ", ",
                    method.Parameters.Select(static parameter =>
                        parameter.IsOptional
                            ? $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueLiteral}"
                            : $"{parameter.TypeName} {parameter.Name}"));

                sb.AppendLine($"    public string {actionMethodName}({parameters})");
                sb.AppendLine("    {");
                sb.AppendLine("        return linkGenerator.GetPathByAction(");
                sb.AppendLine($"            action: \"{method.Name}\",");
                sb.AppendLine($"            controller: \"{controllerName}\",");
                var hasArea = !string.IsNullOrWhiteSpace(controller.AreaName);
                sb.AppendLine(method.Parameters.Length == 0 && !hasArea
                    ? "            values: null)!;"
                    : "            values: new");

                if (method.Parameters.Length > 0 || hasArea)
                {
                    sb.AppendLine("            {");

                    sb.AppendLine(hasArea
                        ? $"                area = \"{EscapeStringLiteral(controller.AreaName!)}\","
                        : "                area = string.Empty,");
                    foreach (var parameter in method.Parameters)
                        sb.AppendLine($"                {parameter.Name},");
                    sb.AppendLine("            })!;");
                }

                sb.AppendLine("    }");
                sb.AppendLine();

                sb.AppendLine(
                    $"    public string {actionMethodName}(HttpContext httpContext{(method.Parameters.Length > 0 ? ", " : string.Empty)}{parameters})");
                sb.AppendLine("    {");
                sb.AppendLine("        return linkGenerator.GetPathByAction(");
                sb.AppendLine("            httpContext,");
                sb.AppendLine($"            action: \"{method.Name}\",");
                sb.AppendLine($"            controller: \"{controllerName}\",");
                sb.AppendLine(method.Parameters.Length == 0 && !hasArea
                    ? "            values: null)!;"
                    : "            values: new");

                if (method.Parameters.Length > 0 || hasArea)
                {
                    sb.AppendLine("            {");

                    if (hasArea)
                        sb.AppendLine($"                area = \"{EscapeStringLiteral(controller.AreaName!)}\",");

                    foreach (var parameter in method.Parameters)
                        sb.AppendLine($"                {parameter.Name},");
                    sb.AppendLine("            })!;");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        foreach (var areaGroup in areaGroups)
        {
            var areaIdentifier = ToIdentifier(areaGroup.Key);
            var areaHelperClassName = $"{areaIdentifier}AreaLinkGenerator";

            sb.AppendLine($"public sealed class {areaHelperClassName}(LinkGenerator linkGenerator)");
            sb.AppendLine("{");

            foreach (var controller in areaGroup.OrderBy(static controller => controller.MetadataName, StringComparer.Ordinal))
            {
                var helperClassName = $"{controller.Name}LinkGenerator";
                var propertyName = controller.Name.Replace("Controller", string.Empty);

                sb.AppendLine($"    public {helperClassName} {propertyName} => new {helperClassName}(linkGenerator);");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("public static class LinkGeneratorExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    extension(LinkGenerator linkGenerator)");
        sb.AppendLine("    {");

        foreach (var controller in nonAreaControllers)
        {
            var helperClassName = $"{controller.Name}LinkGenerator";
            var propertyName = controller.Name.Replace("Controller", string.Empty);

            sb.AppendLine($"        public {helperClassName} {propertyName} => new {helperClassName}(linkGenerator);");
            sb.AppendLine();
        }

        foreach (var areaGroup in areaGroups)
        {
            var areaIdentifier = ToIdentifier(areaGroup.Key);
            var areaHelperClassName = $"{areaIdentifier}AreaLinkGenerator";

            sb.AppendLine($"        public {areaHelperClassName} {areaIdentifier} => new {areaHelperClassName}(linkGenerator);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    private static string ToIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
            return "_";

        var sb = new StringBuilder(value.Length + 1);

        if (!IsIdentifierStart(value[0]))
            sb.Append('_');

        foreach (var c in value)
            sb.Append(IsIdentifierPart(c) ? c : '_');

        var identifier = sb.Length == 0 ? "_" : sb.ToString();
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;
    }

    private static bool IsIdentifierStart(char c) => c == '_' || char.IsLetter(c);

    private static bool IsIdentifierPart(char c) => c == '_' || char.IsLetterOrDigit(c);
}
