using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace EndpointHelpers;

[Generator]
public sealed class LinkGeneratorGenerator : ControllerGeneratorBase
{
    protected override string GenerateAttributeName => "GenerateLinkGeneratorAttribute";
    protected override string IgnoreAttributeName => "LinkGeneratorIgnoreAttribute";
    protected override string OutputFileName => "LinkGeneratorExtensions.g.cs";

    protected override string BuildSource(ImmutableArray<ControllerModel> selectedControllers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EndpointHelpersNamespace};");
        sb.AppendLine();

        foreach (var controller in selectedControllers)
        {
            var controllerName = controller.Name.Replace("Controller", string.Empty);
            var helperClassName = $"{controller.Name}LinkGenerator";

            sb.AppendLine($"public sealed class {helperClassName}(LinkGenerator linkGenerator)");
            sb.AppendLine("{");

            foreach (var method in controller.Methods)
            {
                var actionMethodName = $"Get{method.Name}Path";
                var parameters = string.Join(
                    ", ",
                    method.Parameters.Select(static parameter =>
                        parameter.IsOptional
                            ? $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueLiteral}"
                            : $"{parameter.TypeName} {parameter.Name}"));

                sb.AppendLine($"    public string {actionMethodName}({parameters})");
                sb.AppendLine("    {");
                sb.AppendLine("        return linkGenerator.GetPathByAction(");
                sb.AppendLine($"            action: \"{method.Name}\",");
                sb.AppendLine($"            controller: \"{controllerName}\",");
                sb.AppendLine(method.Parameters.Length == 0
                    ? "            values: null)!;"
                    : "            values: new");

                if (method.Parameters.Length > 0)
                {
                    sb.AppendLine("            {");
                    foreach (var parameter in method.Parameters)
                        sb.AppendLine($"                {parameter.Name},");
                    sb.AppendLine("            })!;");
                }

                sb.AppendLine("    }");
                sb.AppendLine();

                sb.AppendLine(
                    $"    public string {actionMethodName}(HttpContext httpContext{(method.Parameters.Length > 0 ? ", " : string.Empty)}{parameters})");
                sb.AppendLine("    {");
                sb.AppendLine("        return linkGenerator.GetPathByAction(");
                sb.AppendLine("            httpContext,");
                sb.AppendLine($"            action: \"{method.Name}\",");
                sb.AppendLine($"            controller: \"{controllerName}\",");
                sb.AppendLine(method.Parameters.Length == 0
                    ? "            values: null)!;"
                    : "            values: new");

                if (method.Parameters.Length > 0)
                {
                    sb.AppendLine("            {");
                    foreach (var parameter in method.Parameters)
                        sb.AppendLine($"                {parameter.Name},");
                    sb.AppendLine("            })!;");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("public static class LinkGeneratorExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    extension(LinkGenerator linkGenerator)");
        sb.AppendLine("    {");

        foreach (var controller in selectedControllers)
        {
            var helperClassName = $"{controller.Name}LinkGenerator";
            var propertyName = controller.Name.Replace("Controller", string.Empty);

            sb.AppendLine($"        public {helperClassName} {propertyName} => new {helperClassName}(linkGenerator);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
