using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace EndpointHelpers;

[Generator]
public sealed class RedirectToActionGenerator : ControllerGeneratorBase
{
    protected override string GenerateAttributeName => "GenerateRedirectToActionAttribute";
    protected override string IgnoreAttributeName => "RedirectToActionIgnoreAttribute";
    protected override string OutputFileName => "RedirectToActionControllers.g.cs";
    protected override bool SupportsAssemblyGenerateAttribute => false;

    protected override string BuildSource(IReadOnlyList<ControllerModel> selectedControllers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();

        var namespaces = selectedControllers
            .GroupBy(static controller => controller.NamespaceName ?? string.Empty)
            .OrderBy(static group => group.Key, StringComparer.Ordinal);

        foreach (var group in namespaces)
        {
            var hasNamespace = !string.IsNullOrEmpty(group.Key);
            var indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {group.Key}");
                sb.AppendLine("{");
            }

            foreach (var controller in group)
            {
                var controllerName = controller.Name.Replace("Controller", string.Empty);

                sb.AppendLine($"{indent}{controller.AccessibilityKeyword} partial class {controller.Name}");
                sb.AppendLine($"{indent}{{");

                foreach (var method in controller.Methods)
                {
                    var actionMethodName = $"RedirectTo{method.Name}";
                    var parameters = string.Join(
                        ", ",
                        method.Parameters.Select(static parameter =>
                            parameter.IsOptional
                                ? $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueLiteral}"
                                : $"{parameter.TypeName} {parameter.Name}"));

                    sb.AppendLine($"{indent}    public RedirectToActionResult {actionMethodName}({parameters})");
                    sb.AppendLine($"{indent}    {{");

                    if (method.Parameters.Length == 0)
                    {
                        sb.AppendLine($"{indent}        return RedirectToAction(\"{method.Name}\", \"{controllerName}\")!;");
                    }
                    else
                    {
                        sb.AppendLine($"{indent}        return RedirectToAction(");
                        sb.AppendLine($"{indent}            \"{method.Name}\",");
                        sb.AppendLine($"{indent}            \"{controllerName}\",");
                        sb.AppendLine($"{indent}            new RouteValueDictionary");
                        sb.AppendLine($"{indent}            {{");

                        foreach (var parameter in method.Parameters)
                            sb.AppendLine($"{indent}                {{ \"{parameter.Name}\", {parameter.Name} }},");

                        sb.AppendLine(indent + "            })!;");
                    }

                    sb.AppendLine(indent + "    }");
                    sb.AppendLine();
                }

                sb.AppendLine(indent + "}");
                sb.AppendLine();
            }

            if (hasNamespace)
            {
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }
}
