using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace EndpointHelpers;

[Generator]
public sealed class RedirectToActionGenerator : ControllerGeneratorBase
{
    protected override string GenerateAttributeName => "GenerateRedirectToActionAttribute";
    protected override string IgnoreAttributeName => "RedirectToActionIgnoreAttribute";
    protected override string OutputFileName => "RedirectToActionExtensions.g.cs";

    protected override string BuildSource(IReadOnlyList<ControllerModel> selectedControllers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EndpointHelpersNamespace};");
        sb.AppendLine();

        sb.AppendLine("public static class ControllerExtensions");
        sb.AppendLine("{");

        foreach (var controller in selectedControllers)
        {
            sb.AppendLine($"    extension({controller.TypeName} controller)");
            sb.AppendLine("    {");

            var controllerName = controller.Name.Replace("Controller", string.Empty);

            foreach (var method in controller.Methods)
            {
                var actionMethodName = $"RedirectTo{method.Name}";
                var parameters = string.Join(
                    ", ",
                    method.Parameters.Select(static parameter =>
                        parameter.IsOptional
                            ? $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueLiteral}"
                            : $"{parameter.TypeName} {parameter.Name}"));

                sb.AppendLine($"        public RedirectToActionResult {actionMethodName}({parameters})");
                sb.AppendLine("        {");

                if (method.Parameters.Length == 0)
                {
                    sb.AppendLine($"            return controller.RedirectToAction(\"{method.Name}\", \"{controllerName}\")!;");
                }
                else
                {
                    sb.AppendLine("            return controller.RedirectToAction(");
                    sb.AppendLine($"                \"{method.Name}\",");
                    sb.AppendLine($"                \"{controllerName}\",");
                    sb.AppendLine("                new RouteValueDictionary");
                    sb.AppendLine("                {");

                    foreach (var parameter in method.Parameters)
                        sb.AppendLine($"                    {{ \"{parameter.Name}\", {parameter.Name} }},");

                    sb.AppendLine("                })!;");
                }

                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
