using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EndpointHelpers;

[Generator]
public sealed class UrlHelperGenerator : ControllerGeneratorBase
{
    private const string UrlGenerateAttributeName = "GenerateUrlHelperAttribute";
    private const string UrlIgnoreAttributeName = "UrlHelperIgnoreAttribute";
    private const string LinkGenerateAttributeName = "GenerateLinkGeneratorAttribute";
    private const string LinkIgnoreAttributeName = "LinkGeneratorIgnoreAttribute";
    private const string RedirectGenerateAttributeName = "GenerateRedirectToActionAttribute";
    private const string RedirectIgnoreAttributeName = "RedirectToActionIgnoreAttribute";

    protected override string GenerateAttributeName => UrlGenerateAttributeName;
    protected override string IgnoreAttributeName => UrlIgnoreAttributeName;
    protected override string OutputFileName => "UrlHelperExtensions.g.cs";

    //lang=cs
    private const string AttributeSourceCode = $"""
                                                 // <auto-generated/>

                                                 namespace {EndpointHelpersNamespace};
                                                 
                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {UrlGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {UrlIgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {LinkGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {LinkIgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {RedirectGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {RedirectIgnoreAttributeName} : global::System.Attribute;
                                                 
                                                 """;

    protected override void RegisterPostInitialization(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource(
                "Attributes.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });
    }

    protected override string BuildSource(IReadOnlyList<ControllerModel> selectedControllers)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EndpointHelpersNamespace};");
        sb.AppendLine();

        foreach (var controller in selectedControllers)
        {
            var controllerName = controller.Name.Replace("Controller", string.Empty);
            var helperClassName = $"{controller.Name}UrlHelper";

            sb.AppendLine($"public sealed class {helperClassName}(IUrlHelper url)");
            sb.AppendLine("{");

            foreach (var method in controller.Methods)
            {
                var parameters = string.Join(
                    ", ",
                    method.Parameters.Select(static parameter =>
                        parameter.IsOptional
                            ? $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueLiteral}"
                            : $"{parameter.TypeName} {parameter.Name}"));

                sb.AppendLine($"    public string {method.Name}({parameters})");
                sb.AppendLine("    {");

                if (method.Parameters.Length == 0)
                {
                    sb.AppendLine($"        return url.Action(\"{method.Name}\", \"{controllerName}\")!;");
                }
                else
                {
                    sb.AppendLine("        return url.Action(");
                    sb.AppendLine($"            \"{method.Name}\",");
                    sb.AppendLine($"            \"{controllerName}\",");
                    sb.AppendLine("            new RouteValueDictionary");
                    sb.AppendLine("            {");

                    foreach (var parameter in method.Parameters)
                        sb.AppendLine($"                {{ \"{parameter.Name}\", {parameter.Name} }},");

                    sb.AppendLine("            })!;");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("public static class UrlHelperExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    extension(IUrlHelper url)");
        sb.AppendLine("    {");

        foreach (var controller in selectedControllers)
        {
            var helperClassName = $"{controller.Name}UrlHelper";
            var propertyName = controller.Name.Replace("Controller", string.Empty);

            sb.AppendLine($"        public {helperClassName} {propertyName} => new {helperClassName}(url);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
