using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace EndpointHelpers;

[Generator]
public sealed class UrlHelperGenerator : ControllerGeneratorBase
{
    private const string UrlGenerateAttributeName = "GenerateUrlHelperAttribute";
    private const string UrlIgnoreAttributeName = "UrlHelperIgnoreAttribute";
    private const string LinkGenerateAttributeName = "GenerateLinkGeneratorAttribute";
    private const string LinkIgnoreAttributeName = "LinkGeneratorIgnoreAttribute";
    private const string RedirectGenerateAttributeName = "GenerateRedirectToActionAttribute";
    private const string RedirectIgnoreAttributeName = "RedirectToActionIgnoreAttribute";
    private const string ViewGenerateAttributeName = "GenerateViewHelpersAttribute";
    private const string ViewIgnoreAttributeName = "ViewHelpersIgnoreAttribute";

    protected override string GenerateAttributeName => UrlGenerateAttributeName;
    protected override string IgnoreAttributeName => UrlIgnoreAttributeName;
    protected override string OutputFileName => "UrlHelperExtensions.g.cs";

    protected override void RegisterSourceOutput(
        IncrementalGeneratorInitializationContext context,
        IncrementalValuesProvider<ControllerModel> controllers,
        IncrementalValueProvider<bool> assemblyHasGenerate)
    {
        var hasJetbrainsAnnotations = context.CompilationProvider
            .Select(static (compilation, _) =>
                compilation.GetTypeByMetadataName("JetBrains.Annotations.AspMvcControllerAttribute") is not null &&
                compilation.GetTypeByMetadataName("JetBrains.Annotations.AspMvcViewAttribute") is not null);

        context.RegisterSourceOutput(
            controllers.Collect().Combine(assemblyHasGenerate).Combine(hasJetbrainsAnnotations),
            (ctx, data) =>
            {
                var controllers = data.Left.Left;
                var assemblyHasGenerateAttribute = data.Left.Right;
                var hasJetbrains = data.Right;

                Generate(ctx, controllers, assemblyHasGenerateAttribute, hasJetbrains);
            });
    }

    //lang=cs
    private const string AttributeSourceCode = $"""
                                                 // <auto-generated/>

                                                 namespace {EndpointHelpersNamespace};
                                                 
                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {UrlGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {UrlIgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {LinkGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {LinkIgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {RedirectGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {RedirectIgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Class)]
                                                 internal sealed class {ViewGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {ViewIgnoreAttributeName} : global::System.Attribute;
                                                  
                                                 """;

    protected override void RegisterPostInitialization(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource(
                "Attributes.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });
    }

    protected override string BuildSource(
        IReadOnlyList<ControllerModel> selectedControllers,
        bool hasJetbrainsAnnotations = false)
    {
        var nonAreaControllers = selectedControllers
            .Where(static controller => string.IsNullOrWhiteSpace(controller.AreaName))
            .OrderBy(static controller => controller.MetadataName, StringComparer.Ordinal)
            .ToArray();

        var areaGroups = selectedControllers
            .Where(static controller => !string.IsNullOrWhiteSpace(controller.AreaName))
            .GroupBy(static controller => controller.AreaName!, StringComparer.Ordinal)
            .OrderBy(static group => group.Key, StringComparer.Ordinal)
            .ToArray();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();
        sb.AppendLine($"namespace {EndpointHelpersNamespace};");
        sb.AppendLine();

        foreach (var controller in selectedControllers)
        {
            var controllerName = controller.Name.Replace("Controller", string.Empty);
            var helperClassName = $"{controller.Name}UrlHelper";

            sb.AppendLine($"public sealed class {helperClassName}(IUrlHelper url)");
            sb.AppendLine("{");

            foreach (var method in controller.Methods)
            {
                var parameters = string.Join(
                    ", ",
                    method.Parameters.Select(static parameter =>
                        parameter.IsOptional
                            ? $"{parameter.TypeName} {parameter.Name} = {parameter.DefaultValueLiteral}"
                            : $"{parameter.TypeName} {parameter.Name}"));

                if (hasJetbrainsAnnotations)
                    sb.AppendLine("    [global::JetBrains.Annotations.AspMvcActionAttribute]");

                sb.AppendLine($"    public string {method.Name}({parameters})");
                sb.AppendLine("    {");

                var hasArea = !string.IsNullOrWhiteSpace(controller.AreaName);
                if (method.Parameters.Length == 0 && !hasArea)
                {
                    sb.AppendLine($"        return url.Action(\"{method.Name}\", \"{controllerName}\")!;");
                }
                else
                {
                    sb.AppendLine("        return url.Action(");
                    sb.AppendLine($"            \"{method.Name}\",");
                    sb.AppendLine($"            \"{controllerName}\",");
                    sb.AppendLine("            new RouteValueDictionary");
                    sb.AppendLine("            {");

                    sb.AppendLine(hasArea
                        ? $"                {{ \"Area\", \"{EscapeStringLiteral(controller.AreaName!)}\" }},"
                        : "                { \"Area\", string.Empty },");
                    foreach (var parameter in method.Parameters)
                        sb.AppendLine($"                {{ \"{parameter.Name}\", {parameter.Name} }},");

                    sb.AppendLine("            })!;");
                }

                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        foreach (var areaGroup in areaGroups)
        {
            var areaIdentifier = ToIdentifier(areaGroup.Key);
            var areaHelperClassName = $"{areaIdentifier}AreaUrlHelper";

            sb.AppendLine($"public sealed class {areaHelperClassName}(IUrlHelper url)");
            sb.AppendLine("{");

            foreach (var controller in areaGroup.OrderBy(static controller => controller.MetadataName, StringComparer.Ordinal))
            {
                var helperClassName = $"{controller.Name}UrlHelper";
                var propertyName = controller.Name.Replace("Controller", string.Empty);

                if (hasJetbrainsAnnotations)
                    sb.AppendLine("    [global::JetBrains.Annotations.AspMvcControllerAttribute]");

                sb.AppendLine($"    public {helperClassName} {propertyName} => new {helperClassName}(url);");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("public static class UrlHelperExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    extension(IUrlHelper url)");
        sb.AppendLine("    {");

        foreach (var controller in nonAreaControllers)
        {
            var helperClassName = $"{controller.Name}UrlHelper";
            var propertyName = controller.Name.Replace("Controller", string.Empty);

            if (hasJetbrainsAnnotations)
                sb.AppendLine("        [global::JetBrains.Annotations.AspMvcControllerAttribute]");

            sb.AppendLine($"        public {helperClassName} {propertyName} => new {helperClassName}(url);");
            sb.AppendLine();
        }

        foreach (var areaGroup in areaGroups)
        {
            var areaIdentifier = ToIdentifier(areaGroup.Key);
            var areaHelperClassName = $"{areaIdentifier}AreaUrlHelper";

            if(hasJetbrainsAnnotations)
                sb.AppendLine("        [global::JetBrains.Annotations.AspMvcAreaAttribute]");
            
            sb.AppendLine($"        public {areaHelperClassName} {areaIdentifier} => new {areaHelperClassName}(url);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"");
    }

    private static string ToIdentifier(string value)
    {
        if (string.IsNullOrEmpty(value))
            return "_";

        var sb = new StringBuilder(value.Length + 1);

        if (!IsIdentifierStart(value[0]))
            sb.Append('_');

        foreach (var c in value)
            sb.Append(IsIdentifierPart(c) ? c : '_');

        var identifier = sb.Length == 0 ? "_" : sb.ToString();
        return SyntaxFacts.GetKeywordKind(identifier) == SyntaxKind.None ? identifier : "@" + identifier;
    }

    private static bool IsIdentifierStart(char c) => c == '_' || char.IsLetter(c);

    private static bool IsIdentifierPart(char c) => c == '_' || char.IsLetterOrDigit(c);
}
