using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EndpointHelpers;

[Generator]
public sealed class UrlHelperGenerator : IIncrementalGenerator
{
    private const string Namespace = "EndpointHelpers";
    private const string GenerateAttributeName = "GenerateUrlHelperAttribute";
    private const string IgnoreAttributeName = "UrlHelperIgnoreAttribute";
    private const string LinkGenerateAttributeName = "GenerateLinkGeneratorAttribute";
    private const string LinkIgnoreAttributeName = "LinkGeneratorIgnoreAttribute";
    private const string RedirectGenerateAttributeName = "GenerateRedirectToActionAttribute";
    private const string RedirectIgnoreAttributeName = "RedirectToActionIgnoreAttribute";
    private const string UnifiedGenerateAttributeName = "GenerateEndpointHelpersAttribute";
    private const string NonActionAttributeName = "Microsoft.AspNetCore.Mvc.NonActionAttribute";

    //lang=cs
    private const string AttributeSourceCode = $"""
                                                 // <auto-generated/>

                                                 namespace {Namespace};
                                                 
                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {GenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {IgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {LinkGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {LinkIgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {RedirectGenerateAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(global::System.AttributeTargets.Method)]
                                                 internal sealed class {RedirectIgnoreAttributeName} : global::System.Attribute;

                                                 [global::Microsoft.CodeAnalysis.EmbeddedAttribute]
                                                 [global::System.AttributeUsage(
                                                     global::System.AttributeTargets.Method |
                                                     global::System.AttributeTargets.Class |
                                                     global::System.AttributeTargets.Assembly)]
                                                 internal sealed class {UnifiedGenerateAttributeName} : global::System.Attribute;
                                                 
                                                 """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddEmbeddedAttributeDefinition();
            ctx.AddSource(
                "Attributes.g.cs",
                SourceText.From(AttributeSourceCode, Encoding.UTF8));
        });

        var generateTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{GenerateAttributeName}",
                static (node, _) => node is ClassDeclarationSyntax or MethodDeclarationSyntax,
                static (ctx, _) => GetControllerMetadataName(ctx.TargetSymbol))
            .Where(static t => t is not null);

        var unifiedTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                $"{Namespace}.{UnifiedGenerateAttributeName}",
                static (node, _) => node is ClassDeclarationSyntax or MethodDeclarationSyntax,
                static (ctx, _) => GetControllerMetadataName(ctx.TargetSymbol))
            .Where(static t => t is not null);

        var targets = generateTargets
            .Collect()
            .Combine(unifiedTargets.Collect())
            .Select(static (x, _) => x.Left.AddRange(x.Right));

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(targets),
            static (ctx, t) => Generate(ctx, t.Left, t.Right!));
    }

    private static string? GetControllerMetadataName(ISymbol symbol)
    {
        return symbol switch
        {
            INamedTypeSymbol type => GetMetadataName(type),
            IMethodSymbol method => method.ContainingType is null ? null : GetMetadataName(method.ContainingType),
            _ => null
        };
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<string?> members)
    {
        var assemblyHasGenerate = compilation.Assembly.GetAttributes()
            .Any(a => a.AttributeClass?.ToDisplayString() ==
                      $"{Namespace}.{GenerateAttributeName}" ||
                      a.AttributeClass?.ToDisplayString() ==
                      $"{Namespace}.{UnifiedGenerateAttributeName}");

        INamedTypeSymbol[] controllers;

        if (assemblyHasGenerate)
        {
            controllers = GetAllTypes(compilation.GlobalNamespace)
                .Where(t =>
                    t.TypeKind == TypeKind.Class && !t.IsAbstract &&
                    t.Name.EndsWith("Controller"))
                .ToArray();
        }
        else
        {
            if (members.IsDefaultOrEmpty)
                return;

            controllers = members
                .Distinct()
                .Select(name => compilation.GetTypeByMetadataName(name!))
                .Where(s => s is not null)
                .Distinct(SymbolEqualityComparer.Default)
                .Cast<INamedTypeSymbol>()
                .ToArray();
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();

        foreach (var controller in controllers)
        {
            var generateAttr = controller.GetAttributes()
                .FirstOrDefault(a =>
                    a.AttributeClass?.ToDisplayString() ==
                    $"{Namespace}.{GenerateAttributeName}" ||
                    a.AttributeClass?.ToDisplayString() ==
                    $"{Namespace}.{UnifiedGenerateAttributeName}");

            var controllerName = controller.Name.Replace("Controller", "");
            var helperClassName = $"{controller.Name}UrlHelper";

            sb.AppendLine($"public sealed class {helperClassName}(IUrlHelper url)");
            sb.AppendLine("{");

            var methods = controller.GetMembers()
                .OfType<IMethodSymbol>()
                .Where(m =>
                    m.MethodKind == MethodKind.Ordinary &&
                    m.DeclaredAccessibility == Accessibility.Public &&
                    !m.GetAttributes().Any(a =>
                        a.AttributeClass?.ToDisplayString() ==
                        $"{Namespace}.{IgnoreAttributeName}") &&
                    !m.GetAttributes().Any(a =>
                        a.AttributeClass?.ToDisplayString() ==
                        NonActionAttributeName) &&
                    (assemblyHasGenerate ||
                     generateAttr != null ||
                     m.GetAttributes().Any(a =>
                         a.AttributeClass?.ToDisplayString() ==
                         $"{Namespace}.{GenerateAttributeName}" ||
                         a.AttributeClass?.ToDisplayString() ==
                         $"{Namespace}.{UnifiedGenerateAttributeName}")));

            foreach (var method in methods)
            {
                var action = method.Name;

                var parameters = string.Join(
                    ", ",
                    method.Parameters.Select(p =>
                        $"{p.Type.ToDisplayString()} {p.Name}" +
                        (p.IsOptional
                            ? $" = {(p.ExplicitDefaultValue == null
                                ? "null"
                                : p.Type.SpecialType == SpecialType.System_String
                                    ? $"\"{p.ExplicitDefaultValue}\""
                                    : p.ExplicitDefaultValue.ToString())}"
                            : string.Empty)));


                sb.AppendLine($"    public string {action}({parameters})");
                sb.AppendLine("    {");

                if (method.Parameters.Length == 0)
                {
                    sb.AppendLine(
                        $"        return url.Action(\"{action}\", \"{controllerName}\")!;");
                }
                else
                {
                    sb.AppendLine("        return url.Action(");
                    sb.AppendLine($"            \"{action}\",");
                    sb.AppendLine($"            \"{controllerName}\",");
                    sb.AppendLine("            new RouteValueDictionary");
                    sb.AppendLine("            {");

                    foreach (var p in method.Parameters)
                        sb.AppendLine($"                {{ \"{p.Name}\", {p.Name} }},");

                    sb.AppendLine("            })!;");
                }


                sb.AppendLine("    }");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("public static class UrlHelperExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    extension(IUrlHelper url)");
        sb.AppendLine("    {");

        foreach (var controller in controllers)
        {
            var helperClassName = $"{controller.Name}UrlHelper";
            var propertyName = controller.Name.Replace("Controller", "");

            sb.AppendLine($"        public {helperClassName} {propertyName} => new {helperClassName}(url);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource(
            "UrlHelperExtensions.g.cs",
            SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
            yield return type;

        foreach (var nested in ns.GetNamespaceMembers())
        foreach (var type in GetAllTypes(nested))
            yield return type;
    }

    private static string GetMetadataName(INamedTypeSymbol type)
    {
        var name = type.MetadataName;
        var current = type.ContainingType;

        while (current is not null)
        {
            name = $"{current.MetadataName}+{name}";
            current = current.ContainingType;
        }

        var ns = type.ContainingNamespace?.ToDisplayString();
        return string.IsNullOrEmpty(ns) ? name : $"{ns}.{name}";
    }
}
