using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EndpointHelpers;

[Generator]
public sealed class ViewGenerator : ControllerGeneratorBase
{
    protected override string GenerateAttributeName => "GenerateViewHelpersAttribute";
    protected override string IgnoreAttributeName => "ViewHelpersIgnoreAttribute";
    protected override string OutputFileName => "ViewHelpers.g.cs";
    protected override bool SupportsAssemblyGenerateAttribute => false;

    protected override void RegisterSourceOutput(
        IncrementalGeneratorInitializationContext context,
        IncrementalValuesProvider<ControllerModel> controllers,
        IncrementalValueProvider<bool> assemblyHasGenerate)
    {
        var additionalViews = context.AdditionalTextsProvider
            .Where(static text => text.Path.EndsWith(".cshtml", StringComparison.OrdinalIgnoreCase))
            .Select(static (text, _) => ExtractViewInfo(text.Path))
            .Collect();

        var hasJetbrainsAnnotations = context.CompilationProvider
            .Select(static (compilation, _) =>
                compilation.GetTypeByMetadataName("JetBrains.Annotations.AspMvcViewAttribute") is not null &&
                compilation.GetTypeByMetadataName("JetBrains.Annotations.AspMvcActionAttribute") is not null &&
                compilation.GetTypeByMetadataName("JetBrains.Annotations.AspMvcModelTypeAttribute") is not null);

        var viewMap = context.CompilationProvider
            .Combine(additionalViews)
            .Combine(hasJetbrainsAnnotations)
            .Select(static (data, _) => (
                Views: BuildViewMap(data.Left.Left, data.Left.Right),
                HasJetbrains: data.Right));

        context.RegisterSourceOutput(
            controllers.Collect().Combine(viewMap),
            (ctx, data) =>
            {
                var rawControllers = data.Left;
                var viewsByController = data.Right.Views;
                var hasJetbrains = data.Right.HasJetbrains;

                var selected = SelectControllers(rawControllers, assemblyHasGenerate: false)
                    .Where(static c => c.ClassHasGenerateAttribute)
                    .Select(controller =>
                    {
                        var controllerKey = TrimControllerSuffix(controller.Name);
                        var views = viewsByController.TryGetValue(controllerKey, out var found)
                            ? found
                            : ImmutableArray<string>.Empty;

                        return controller with
                        {
                            Methods = [
                                ..views
                                    .Select(viewName => new ActionModel(
                                        viewName,
                                        HasGenerateAttribute: false,
                                        Parameters: ImmutableArray<ParameterModel>.Empty))
                            ]
                        };
                    })
                    .Where(static c => c.Methods.Length > 0)
                    .ToImmutableArray();

                if (selected.Length == 0)
                    return;

                ctx.AddSource(
                    OutputFileName,
                    SourceText.From(BuildSource(selected, hasJetbrains), Encoding.UTF8));
            });
    }

    protected override string BuildSource(
        IReadOnlyList<ControllerModel> selectedControllers,
        bool hasJetbrainsAnnotations = false)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();

        var namespaces = selectedControllers
            .GroupBy(static controller => controller.NamespaceName ?? string.Empty)
            .OrderBy(static group => group.Key, System.StringComparer.Ordinal);

        foreach (var group in namespaces)
        {
            var hasNamespace = !string.IsNullOrEmpty(group.Key);
            var indent = hasNamespace ? "    " : string.Empty;

            if (hasNamespace)
            {
                sb.AppendLine($"namespace {group.Key}");
                sb.AppendLine("{");
            }

            foreach (var controller in group)
            {
                sb.AppendLine($"{indent}{controller.AccessibilityKeyword} partial class {controller.Name}");
                sb.AppendLine($"{indent}{{");

                var methodAccess = controller.IsSealed ? "private" : "protected";

                foreach (var method in controller.Methods)
                {
                    var methodName = $"{method.Name}View";

                    if (hasJetbrainsAnnotations)
                        sb.AppendLine($"{indent}    [global::JetBrains.Annotations.AspMvcViewAttribute]");

                    sb.AppendLine($"{indent}    {methodAccess} ViewResult {methodName}()");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        return new ViewResult");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            ViewName = \"{method.Name}\",");
                    sb.AppendLine($"{indent}            ViewData = ViewData,");
                    sb.AppendLine($"{indent}            TempData = TempData");
                    sb.AppendLine($"{indent}        }};");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();

                    if (hasJetbrainsAnnotations)
                        sb.AppendLine($"{indent}    [global::JetBrains.Annotations.AspMvcViewAttribute]");
                    sb.AppendLine(
                        $"{indent}    {methodAccess} ViewResult {methodName}({(hasJetbrainsAnnotations ? "[global::JetBrains.Annotations.AspMvcModelTypeAttribute] " : string.Empty)}object? model)");
                    sb.AppendLine($"{indent}    {{");
                    sb.AppendLine($"{indent}        ViewData.Model = model;");
                    sb.AppendLine($"{indent}        return new ViewResult");
                    sb.AppendLine($"{indent}        {{");
                    sb.AppendLine($"{indent}            ViewName = \"{method.Name}\",");
                    sb.AppendLine($"{indent}            ViewData = ViewData,");
                    sb.AppendLine($"{indent}            TempData = TempData");
                    sb.AppendLine($"{indent}        }};");
                    sb.AppendLine($"{indent}    }}");
                    sb.AppendLine();
                }

                sb.AppendLine($"{indent}}}");
                sb.AppendLine();
            }

            if (hasNamespace)
            {
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static ImmutableDictionary<string, ImmutableArray<string>> BuildViewMap(
        Compilation compilation,
        ImmutableArray<ViewInfo?> additionalViews)
    {
        var builder = ImmutableDictionary.CreateBuilder<string, ImmutableArray<string>>(StringComparer.OrdinalIgnoreCase);
        var temp = new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);

        var assemblies = new List<IAssemblySymbol> { compilation.Assembly };
        assemblies.AddRange(compilation.SourceModule.ReferencedAssemblySymbols);

        foreach (var assembly in assemblies)
        {
            foreach (var type in EnumerateTypes(assembly.GlobalNamespace))
            {
                if (!IsRazorPage(type))
                    continue;

                var tokens = type.Name.Split('_');
                if (tokens.Length < 2)
                    continue;

                var controller = tokens[^2];
                var view = tokens[^1];

                if (controller.Equals("Shared", StringComparison.OrdinalIgnoreCase))
                    continue;

                if (!temp.TryGetValue(controller, out var set))
                {
                    set = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                    temp[controller] = set;
                }

                set.Add(view);
            }
        }

        foreach (var kvp in temp)
            builder[kvp.Key] = [.. kvp.Value.OrderBy(static v => v, StringComparer.Ordinal)];

        if (!additionalViews.IsDefaultOrEmpty)
        {
            foreach (var view in additionalViews)
            {
                if (view is null)
                    continue;

                if (!builder.TryGetValue(view.Value.Controller, out var existing))
                {
                    builder[view.Value.Controller] = [view.Value.View];
                    continue;
                }

                if (!existing.Contains(view.Value.View, StringComparer.OrdinalIgnoreCase))
                    builder[view.Value.Controller] = existing.Add(view.Value.View);
            }
        }

        return builder.ToImmutable();
    }

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamespaceSymbol ns)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;

            foreach (var nested in EnumerateTypes(type))
                yield return nested;
        }

        foreach (var child in ns.GetNamespaceMembers())
        {
            foreach (var nested in EnumerateTypes(child))
                yield return nested;
        }
    }

    private static ViewInfo? ExtractViewInfo(string path)
    {
        var segments = path.Split(new[] { '/', '\\' }, StringSplitOptions.RemoveEmptyEntries);
        var viewsIndex = Array.IndexOf(segments, "Views");
        if (viewsIndex < 0 || viewsIndex + 2 >= segments.Length)
            return null;

        var controller = segments[viewsIndex + 1];
        var viewWithExt = segments[viewsIndex + 2];
        var dot = viewWithExt.LastIndexOf('.');
        var view = dot >= 0 ? viewWithExt[..dot] : viewWithExt;

        if (controller.Equals("Shared", StringComparison.OrdinalIgnoreCase))
            return null;

        return new ViewInfo(controller, view);
    }

    private readonly record struct ViewInfo(string Controller, string View);

    private static IEnumerable<INamedTypeSymbol> EnumerateTypes(INamedTypeSymbol type)
    {
        foreach (var nested in type.GetTypeMembers())
        {
            yield return nested;

            foreach (var child in EnumerateTypes(nested))
                yield return child;
        }
    }

    private static bool IsRazorPage(INamedTypeSymbol type)
    {
        var current = type;
        while (current is not null)
        {
            if (current.Name is "RazorPage" &&
                current.ContainingNamespace?.ToDisplayString() == "Microsoft.AspNetCore.Mvc.Razor")
                return true;

            current = current.BaseType;
        }

        return false;
    }

    private static string TrimControllerSuffix(string name)
    {
        return name.EndsWith("Controller", StringComparison.Ordinal)
            ? name[..^"Controller".Length]
            : name;
    }
}
